#!/usr/bin/env bash

set -ex

DEFAULT_VERSION="0.1.5"
libyaml_version=${1:-$DEFAULT_VERSION}

if [ -z "$libyaml_version" ]; then
    echo "Usage: $(basename "$0") VERSION" >&2
    exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$S3_BUCKET" ]; then
    echo "Must set S3_BUCKET environment variable" >&2
    exit 1
fi

tempdir="$( mktemp -t libyaml_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "-----> Downloading libyaml ${libyaml_version}"
curl -L "http://pyyaml.org/download/libyaml/yaml-${libyaml_version}.tar.gz" | tar xzv

build_cmd=$(cat <<SH
    mkdir -p /app/vendor/libyaml \
    && cd yaml-${libyaml_version} \
    && ./configure --prefix=/app/vendor/libyaml \
    && make && make install
SH
)

vulcan build --verbose \
    --prefix /app/vendor/libyaml \
    --source "$tempdir" \
    --output "${tempdir}/libyaml-${libyaml_version}.tgz" \
    --name libyaml \
    --command "$build_cmd"

s3_path=s3://$S3_BUCKET/package/libyaml-${libyaml_version}.tgz

echo "-----> Uploading package to ${s3_path}"

s3cmd put \
    --verbose --acl-public \
    "$tempdir/libyaml-${libyaml_version}.tgz" \
    "${s3_path}"

"$basedir/package-checksum" "libyaml-${libyaml_version}"

echo "-----> Done building libyaml package!"