#!/usr/bin/env bash

php_memcached_version=40ce9b4633de5d70f056e4d434d9b064263348d0
LIBMEMCACHED_VERSION="1.0.18";

MEMCACHED_LIB_DIR=/app/vendor/php/lib/libmemcached
mkdir -p $MEMCACHED_LIB_DIR
curl "http://${S3_BUCKET}.s3.amazonaws.com/package/libmemcached-${LIBMEMCACHED_VERSION}.tgz" \
    | tar xzv -C $MEMCACHED_LIB_DIR
cp -a $MEMCACHED_LIB_DIR $PREFIX/lib/libmemcached

curl -L "https://github.com/andreiz/php-memcached/archive/${php_memcached_version}.tar.gz" \
    | tar xzv
cd php-memcached-${php_memcached_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --with-libmemcached-dir=$MEMCACHED_LIB_DIR \
            --enable-memcached

make
cp modules/memcached.so "$EXT_DIR/memcached.so"
echo "extension=memcached.so" > "$PREFIX/etc/conf.d/memcached.ini"
