#!/usr/bin/env bash

set -e
set -x

DEFAULT_VERSION=1.3.1
PHALCON_VERSION=${1:-$DEFAULT_VERSION}

PATH=$PATH:/app/vendor/php/bin/
git clone --depth 1 -b phalcon-v${PHALCON_VERSION} \
    git://github.com/phalcon/cphalcon.git

cd cphalcon/build && ./install

# The 'install' command puts the module .so file
# in /app/vendor/php/lib/php/extensions/no-debug-non-zts-VERSION/
cp -v /app/vendor/php/lib/php/extensions/no-debug-non-zts-*/phalcon.so "$EXT_DIR/phalcon.so"
echo "extension=phalcon.so" > "$PREFIX/etc/conf.d/phalcon.ini"

