#!/usr/bin/env bash

set -e
set -x

DEFAULT_VERSION=1.3.1
PHALCON_VERSION=${1:-$DEFAULT_VERSION}

PATH=$PATH:/app/vendor/php/bin/
git clone --depth 1 -b phalcon-v${PHALCON_VERSION} \
    git://github.com/phalcon/cphalcon.git

cd cphalcon/build && ./install

ls -al modules/ || true
# cp modules/phalcon.so "$EXT_DIR/phalcon.so"
echo "extension=phalcon.so" > "$PREFIX/etc/conf.d/phalcon.ini"

