#!/usr/bin/env bash

set -e

ext_yaml_version=1.1.1
libyaml_version=0.1.5

# Get libyaml and copy it to our out directory
YAML_LIB_DIR=/app/vendor/php/lib/libyaml
mkdir -p $YAML_LIB_DIR
curl "http://${S3_BUCKET}.s3.amazonaws.com/package/libyaml-${libyaml_version}.tgz" \
    | tar xzv -C $YAML_LIB_DIR
cp -a $YAML_LIB_DIR $PREFIX/lib/libyaml

# Get and build the extension
curl -L "http://pecl.php.net/get/yaml-${ext_yaml_version}.tgz" \
    | tar xzv
cd yaml-${ext_yaml_version}
/app/vendor/php/bin/phpize
./configure --with-php-config=/app/vendor/php/bin/php-config \
            --with-yaml=$YAML_LIB_DIR
make
cp modules/yaml.so "$EXT_DIR/yaml.so"
echo "extension=yaml.so" > "$PREFIX/etc/conf.d/yaml.ini"

